---
title: "Looking at some outputs from DESeq2"
output: html_document
---

```{r}
library(DESeq2)
library(multiseq)
library(pROC)

#set path
path = "D:/Grad School/GitHub/multiseq_simulation"

#load utilities
source(file.path(path, "src/utils.R"))
source(file.path(path, "src/agg_counts.R"))

#read in list of regions
list.loci.sheet = "src/list_loci_sim_encode_all_11"
list.loci = read.table(file.path(path, list.loci.sheet))

#set parameters
win.size=list.loci[1,3]-list.loci[1,2]
N=dim(list.loci)[1]

#read in data
data.null.sim=NULL
data.alt.sim=NULL

for(i in 1:N){
  load(file.path(path,"data",paste(list.loci[i,1],list.loci[i,2]+1,list.loci[i,3],sep="."),"sim_res.Robj"))
  sim.data=t(agg.counts(data.null,win.size))
  data.null.sim=rbind(data.null.sim,sim.data)
  sim.data=t(agg.counts(data.alt,win.size))
  data.alt.sim=rbind(data.alt.sim,sim.data)
}


#run DESeq2
data.sim=rbind(data.null.sim,data.alt.sim)


data.info=data.frame(t=factor(g,labels=c("A","B")))
sim.y.m=DESeqDataSetFromMatrix(countData = data.sim, colData = data.info, design = formula(~t))
sizeFactors(sim.y.m)=read.depth.null
sim.y=estimateDispersionsGeneEst(sim.y.m)
dispersions(sim.y)=mcols(sim.y)$dispGeneEst
sim.y=nbinomWaldTest(sim.y)
#sim.y=DESeq(sim.y.m, fitType="local") #local because parametric fit results in warning
res=results(sim.y)
```


```{r}
#look at p-values
pval.sep = 0
for(i in 1:(2*N)){
  fit = glm(data.sim[i, ] ~ g, family = "poisson")
  pval.sep[i] = summary(fit)$coef[2, 4]
}

par(mfrow = c(2, 1))
plot(pval.sep, ylab = "p-value", main = "Based on data (separate for each region)")
abline(v = 118, lty = 2)
plot(res$pvalue, ylab = "p-value", main = "Based on DESeq2")
abline(v = 118, lty = 2)
```

```{r}
roc.res.sep = roc(controls = pval.sep[1:N], cases = pval.sep[(N+1):(2*N)])
roc.res.DESeq2 = roc(controls = res$pvalue[1:N], cases = res$pvalue[(N+1):(2*N)])

plot(roc.res.sep, main = "ROC curves")
lines(roc.res.DESeq2, col = 2)
legend("bottomright", legend = c("separate", "DESeq2"), lty = c(1, 1), col = 1:2)
```



We then look at the case when there are many more null simulations than alternatives (10:1)

```{r}
N=dim(list.loci)[1]

#read in data
data.null.sim=NULL
data.alt.sim=NULL

for(i in 1:N){
  load(file.path(path,"data",paste(list.loci[i,1],list.loci[i,2]+1,list.loci[i,3],sep="."),"sim_res_many_null.Robj"))
  for(k in 1:10){
    sim.data=t(agg.counts(data.null[[k]],win.size))
    data.null.sim=rbind(data.null.sim,sim.data)
  }
  sim.data=t(agg.counts(data.alt,win.size))
  data.alt.sim=rbind(data.alt.sim,sim.data)
}


#run DESeq2
data.sim=rbind(data.null.sim,data.alt.sim)


data.info=data.frame(t=factor(g,labels=c("A","B")))
sim.y.m=DESeqDataSetFromMatrix(countData = data.sim, colData = data.info, design = formula(~t))
sizeFactors(sim.y.m)=read.depth.null
sim.y=estimateDispersionsGeneEst(sim.y.m)
dispersions(sim.y)=mcols(sim.y)$dispGeneEst
sim.y=nbinomWaldTest(sim.y)
#sim.y=DESeq(sim.y.m, fitType="local") #local because parametric fit results in warning
res=results(sim.y)

```


```{r}
N = dim(data.sim)[1]

#look at p-values
pval.sep = 0
for(i in 1:N){
  fit = glm(data.sim[i, ] ~ g, family = "poisson")
  pval.sep[i] = summary(fit)$coef[2, 4]
}

par(mfrow = c(2, 1))
plot(pval.sep[1001:length(pval.sep)], ylab = "p-value", main = "Based on data (separate for each region)")
abline(v = 117*10-1000, lty = 2)
plot(res$pvalue[1001:length(pval.sep)], ylab = "p-value", main = "Based on DESeq2")
abline(v = 117*10-1000, lty = 2)
```


```{r}
roc.res.sep = roc(controls = pval.sep[1:dim(data.null.sim)[1]], cases = pval.sep[(dim(data.null.sim)[1]+1):N])
roc.res.DESeq2 = roc(controls = res$pvalue[1:dim(data.null.sim)[1]], cases = res$pvalue[(dim(data.null.sim)[1]+1):N])

plot(roc.res.sep, main = "ROC curves")
lines(roc.res.DESeq2, col = 2)
legend("bottomright", legend = c("separate", "DESeq2"), lty = c(1, 1), col = 1:2)
```